### ISSUE TITLE
Виджет больше не нужен :)

### ISSUE THREAD

**Issue by subbbotin** [lmoroz/foxford#1]
Инженеры Фоксфорда сделали отображение ФИО репетитора и уровня доступа в разделе программ обучения в личном кабинете.
<img width="926" alt="yhplpu" src="https://user-images.githubusercontent.com/7643004/95584000-a9a33a00-0a45-11eb-959e-f92ae31492c9.png">

**Comment by lmoroz** [comment]
Ок, спасибо за уведомление %-)
